version: '3.0'
services:
  mysql:
    container_name: database_mysql
    image: mysql:5.7 
    command: --init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    volumes:
        - ./src/database_init/init.sql:/data/application/init.sql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database_test
      - TZ=America/Sao_paulo
    networks: 
            - net
    depends_on:
      - redis
  redis:  
    image: redis:latest
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks: 
      - net
networks:
    net:
        # use the bridge driver, but enable IPv6
        driver: bridge